name: VMFormValidator
author: Virtuosi Media
category: Forms
tags: [validation, errors, interface]
#docs: http://www.virtuosimedia.com/dev/javascript/vmformvalidator
#demo: http://www.virtuosimedia.com/dev/javascript/vmformvalidator
#current: 1.0