name: VMFormValidator
author: Virtuosi Media
category: Forms
tags: [validation, errors, interface]
#docs: http://www.virtuosimedia.com/dev/javascript/mootools-plugins/vm-form-validator/vm-form-validator-api-documentation
#demo: http://www.virtuosimedia.com/dev/javascript/mootools-plugins/vm-form-validator/vm-form-validator-demos
#current: 1.0